[INFORMATION]
[TITLE]
[AUTHOR]
[SOURCE]
[PRG]
[FILEPATH]
[DELAY]0
[CD TRACK]0
[COMMENT]
[END INFORMATION]
[SUBTITLE]
[COLF]&HFFFFFF,[STYLE]bd,[SIZE]24,[FONT]Tahoma
00:00:02.51,00:00:05.22
[ Chorus ][br]" The Simpsons "

00:00:05.22,00:00:06.24
[ Tires Screeching ]

00:00:08.46,00:00:10.29
D'oh![br][ Screams ]

00:00:37.40,00:00:39.61
[ Alarms Blaring ]

00:00:40.80,00:00:42.54
[ Woman's Voice On P.A. System ][br]Core meltdown in 1 0 seconds.

00:00:43.43,00:00:44.07
Nine, eight--

00:00:45.08,00:00:46.74
- [ Alarms Stop ][br]- Meltdown averted. Good boy.!

00:00:49.16,00:00:51.20
[ Moaning, Yawning ]

00:00:51.93,00:00:55.22
[ Snoring, Purring ]

00:00:59.40,00:01:00.35
[ Buzzes ]

00:01:00.94,00:01:02.70
[ Mr. Burns Groaning ][br]What?

00:01:03.04,00:01:04.60
How dare you disturb me[br]during nap time?

00:01:04.92,00:01:06.55
We're from[br]the Nuclear Regulatory Commission.

00:01:06.84,00:01:08.66
This is a surprise test[br]of worker competence.

00:01:09.26,00:01:10.66
There must be some mistake.

00:01:10.98,00:01:12.92
We, uh-- We make cookies here.

00:01:13.43,00:01:16.49
Mr. Burns's Old-Fashioned[br]Good-Time Extra-Chewy--

00:01:16.87,00:01:18.21
Get the ax.

00:01:21.39,00:01:24.14
The watchdog of public safety.[br]Is there any lower form of life?

00:01:24.61,00:01:28.60
Don't worry, sir. I rounded up our less-gifted[br]employees and led them into the basement.

00:01:30.38,00:01:31.25
- [ Dripping ][br]- [ Mouse Squeaking ]

00:01:31.93,00:01:33.36
Duh, Homer, why are we down here?

00:01:33.79,00:01:37.25
Oh, geez! I told ya, Bernie--[br]to guard the bee!

00:01:37.63,00:01:40.07
- But why?[br]- Oh, you guys are pathetic.

00:01:40.07,00:01:42.73
No wonder Smithers[br]made me head bee guy.

00:01:45.26,00:01:48.10
- Uh, it's gettin' away.[br]- Oh, we did bad!

00:01:49.28,00:01:51.36
- [ Buzzing ][br]- Hey! Uhh! Oh! Hey! Come back!

00:01:51.96,00:01:53.79
Is there a Homer Simpson present?

00:01:54.22,00:01:56.27
No, I'm afraid[br]he couldn't ''bee'' here.

00:01:56.62,00:01:58.24
[ Both Chuckling ]

00:01:58.59,00:01:59.88
Oh, yes, he's in Geneva...

00:02:00.17,00:02:01.98
chairing a conference[br]on nuclear fission.

00:02:02.53,00:02:04.35
[ Mutters ][br]Yes, that should stick.

00:02:04.79,00:02:06.12
D'oh![br]The bee bit my bottom!

00:02:06.63,00:02:08.31
Now my bottom's big!

00:02:07.96,00:02:08.87
[ Sighs ]

00:02:09.34,00:02:11.42
Homer, this is an exact replica[br]of your workstation.

00:02:11.42,00:02:12.12
[ Quietly ][br]Hmm?

00:02:12.55,00:02:15.85
Now we're going to simulate[br]a power surge in core sector 8.

00:02:16.54,00:02:17.99
What the hell are you talking about?

00:02:19.95,00:02:22.07
What do I do? What do I do?[br][ Sobbing ]

00:02:22.99,00:02:24.95
In the name of God,[br]you've gotta tell me!

00:02:25.77,00:02:28.29
Relax. It's just a simulator.[br]Nothing can go wrong.

00:02:28.72,00:02:30.60
[ Muttering ] Just poke blindly[br]at the controls until they let you go.

00:02:33.08,00:02:35.22
- [ Rumbling ][br]- Oh! Ohh!

00:02:36.00,00:02:37.97
Oh, no. No![br]This can't be happening!

00:02:39.32,00:02:40.63
[ Bystanders Screaming ]

00:02:41.08,00:02:42.11
[ Gasps ]

00:02:45.43,00:02:47.44
For the love of God, sir![br]There are two seats!

00:02:47.83,00:02:49.23
I like to put my feet up.

00:02:53.57,00:02:54.35
[ Mr. Burns Groaning ]

00:03:01.46,00:03:02.94
[ Roaring ]

00:03:03.92,00:03:06.64
Must destroy mankind.

00:03:07.14,00:03:08.60
- [ Beeping ][br]- Ooh! Lunchtime. [ Blubbering ]

00:03:11.85,00:03:13.74
We're still not sure[br]how he caused the meltdown.

00:03:14.15,00:03:15.74
There wasn't[br]any nuclear material in the truck!

00:03:16.23,00:03:17.94
Very well.[br]It's time for your bribe.

00:03:18.16,00:03:21.43
Now, you can either have the washer and[br]dryer where the lovely Smithers is standing...

00:03:21.89,00:03:25.24
or you can trade it all in[br]for what's in this box.

00:03:25.67,00:03:26.53
The box.[br]The box!

00:03:26.94,00:03:30.95
Burns, this is a big problem. You just can't[br]throw money at it and make it go away.

00:03:31.38,00:03:33.73
Gentlemen, I've decided[br]there will be no investigation.

00:03:34.10,00:03:35.68
Now, if you'll excuse me,[br]I'll go away.

00:03:35.99,00:03:39.85
You're in big trouble, Burns. Simpson's job[br]requires college training in nuclear physics.

00:03:40.28,00:03:43.26
You get your man up to speed,[br]or we'll be forced to take legal action.

00:03:43.66,00:03:44.87
Is that so?

00:03:45.23,00:03:46.75
Well, I have the feeling you'll be...

00:03:47.06,00:03:49.31
dropping the charges.

00:03:51.83,00:03:54.14
- The painters moved your desk, sir.[br]- Oh, yes.

00:03:55.31,00:03:55.90
[ Doorbell Rings ]

00:03:57.96,00:04:02.26
Hello, Simpson. My lawyers and I were in[br]the neighborhood and thought we'd stop by.

00:04:02.68,00:04:05.36
Would you like to come in[br]for tea and marshmallow squares?

00:04:06.31,00:04:08.69
- [ All Murmuring ][br]- Yes, he would.

00:04:09.51,00:04:11.35
- So you want me to go to college?[br]- College?

00:04:11.83,00:04:13.88
- Ha! Barber or clown?[br]- Bart!

00:04:14.42,00:04:16.27
Remember, your job[br]and the future of your family...

00:04:16.57,00:04:19.12
hinges on your successful completion[br]of Nuclear Physics 1 01 .

00:04:19.89,00:04:21.17
Oh, and one more thing.

00:04:22.34,00:04:23.70
You must find the jade monkey...

00:04:24.22,00:04:26.20
before the next full moon.

00:04:26.64,00:04:28.27
Actually, sir,[br]we found the jade monkey.

00:04:28.60,00:04:30.08
It was in your glove compartment.

00:04:30.38,00:04:32.30
- And the road maps and ice scraper?[br]- They were in there too, sir.

00:04:32.78,00:04:34.08
Excellent!

00:04:34.40,00:04:36.40
It's all falling into place.

00:04:37.14,00:04:39.68
I think this is a great opportunity.[br]You could learn so much.

00:04:40.10,00:04:42.82
Maybe you're right.[br]I did always want to go to college.

00:04:45.67,00:04:47.82
Dad, don't let these[br]application essays throw you.

00:04:48.29,00:04:51.87
Let's see: ''List your three favorite books[br]and how they've influenced your life.''

00:04:52.32,00:04:54.45
- Is TVGuide a book? Son of Sniglet?[br]- No. No.

00:04:54.81,00:04:56.04
- Katherine Hepburn's Me?[br]- No!

00:04:56.65,00:04:57.86
Ohh! I suck!

00:04:58.76,00:05:03.17
It was the most I ever threw up,[br]and it changed my life forever.

00:05:03.57,00:05:04.58
You the man, Homer!

00:05:04.96,00:05:07.42
Thanks, boy.[br]Now for the crowning touch.

00:05:10.25,00:05:12.13
I don't know, Dad.[br]Don't you have a better picture?

00:05:12.47,00:05:14.41
Relax. A photo[br]can't make any difference.

00:05:16.77,00:05:18.12
- He looks crazy.[br]- Agreed.

00:05:19.03,00:05:20.85
Reading his essay would[br]only waste valuable seconds.

00:05:21.71,00:05:23.58
[ TV.:Announcer ] Finally,[br]the great taste of Worcestershire Sauce...

00:05:23.94,00:05:25.39
in a soft drink.!

00:05:25.74,00:05:27.09
[ TV.:Man ][br]Ahh.! Steaky.!

00:05:27.50,00:05:30.00
Sorry, son, but there's a program[br]about campus life that I really should watch.

00:05:30.73,00:05:32.60
We now return to[br]School of Hard Knockers...

00:05:33.06,00:05:34.36
starring Corey Masterson.

00:05:35.60,00:05:38.77
Dean Bitterman, I hope nothing[br]unsavory happens during my visit.

00:05:39.20,00:05:41.58
As you know, I am the president[br]of the United States.

00:05:41.94,00:05:46.24
Oh, don't worry. I've expelled[br]those rowdy members of Chug-a-Lug House.

00:05:46.91,00:05:49.15
Oh, I hate that lousy dean.

00:05:51.65,00:05:53.29
Your bra bomb better work, Nerdlinger.

00:05:53.54,00:05:54.75
- Mm-kay![br]- [ Explosion ]

00:05:56.88,00:05:58.58
[ Gasps ]

00:05:59.32,00:05:59.96
Cory!

00:06:01.07,00:06:02.19
[ Chuckles ][br]Don't worry, Mr. President.

00:06:02.70,00:06:05.25
I-- Mr. President!

00:06:05.63,00:06:06.93
Lighten up, Bitterman!

00:06:07.33,00:06:09.50
That youngster will make[br]a perfect addition to my cabinet.

00:06:09.91,00:06:12.11
Secretary of partying down!

00:06:13.37,00:06:14.95
[ Angry Growling ]

00:06:16.52,00:06:18.28
Yes! Take that, Bitterman!

00:06:19.00,00:06:21.40
Homie, here are the responses[br]from the colleges you applied to.

00:06:23.01,00:06:23.68
D'oh!

00:06:24.56,00:06:26.30
D'oh! D'oh!

00:06:27.01,00:06:28.97
Whoo-hoo![br]A flyer for a hardware store!

00:06:29.73,00:06:31.75
- D'oh![br]- Pop, what are you gonna do?

00:06:32.14,00:06:35.47
Something I should have done[br]a long time ago.

00:06:37.64,00:06:39.96
- You don't know, do you?[br]- No, ma'am.

00:06:40.44,00:06:41.43
Don't worry, Simpson.

00:06:42.41,00:06:45.71
It just so happens[br]I have a chair at Springfield University.

00:06:47.82,00:06:49.59
[ Growling ]

00:06:50.02,00:06:51.75
I'm sorry, Mr. Burns,[br]but I must object.

00:06:52.11,00:06:54.59
- This Simpson is not qualified.[br]- [ All Murmuring Agreement ]

00:06:55.09,00:06:56.18
- [ Continues Growling ][br]- I see.

00:06:56.60,00:06:59.27
Well, you know, fellas, I look at[br]the admissions board a lot like a baseball team.

00:06:59.52,00:07:01.03
You all like baseball, don't you?

00:07:01.60,00:07:03.11
[ All Murmuring Agreement ]

00:07:03.54,00:07:06.78
Yes, well, to have a successful baseball club[br]you need teamwork.

00:07:07.90,00:07:10.93
Not some hot-dog admissions officer[br]playing by his own rules!

00:07:12.30,00:07:14.60
[ Grunting ]

00:07:14.60,00:07:16.12
Excuse me.[br]What are you doing?

00:07:17.36,00:07:18.15
[ Grunting Continues ]

00:07:18.21,00:07:20.65
I'm giving you[br]the beating of your life!

00:07:21.05,00:07:22.46
Look, if--[br]Stop that.

00:07:22.82,00:07:24.62
If you wanted him that badly,[br]why didn't you just say so?

00:07:25.33,00:07:26.61
[ Yells ]

00:07:27.23,00:07:29.24
Smithers, dismember the corpse[br]and send his widow a corsage.

00:07:29.80,00:07:31.41
Whoo-hoo![br]I'm a college man!

00:07:32.47,00:07:34.71
I won't need[br]my high school diploma anymore!

00:07:35.52,00:07:37.52
" I am so smart[br]I am so smart "

00:07:37.96,00:07:40.70
" I am so smart[br]I am so smart "

00:07:41.10,00:07:44.09
" S-M-R-T[br]I mean, S-M-A-R-R-T "

00:07:50.42,00:07:53.96
My first day of college.[br]I wish my father was alive to see this.

00:07:54.40,00:07:55.46
Hey!

00:07:55.76,00:07:57.25
- How long have you been back there?[br]- Three days.

00:07:59.91,00:08:01.39
Nerd!

00:08:02.88,00:08:04.43
Homer--[br]That isn't very nice.

00:08:04.95,00:08:06.34
Marge, try to understand.

00:08:06.68,00:08:09.67
There are two kinds of college students:[br]jocks and nerds.

00:08:09.92,00:08:13.83
As a jock, it is my duty[br]to give nerds a hard time.

00:08:14.36,00:08:17.44
- Hey, pal! Did you get a load of the nerd?[br]- Pardon me?

00:08:18.54,00:08:19.91
" [ Rock ]

00:08:29.21,00:08:30.86
I'll be a campus hero.

00:08:35.41,00:08:36.46
[ Spits ][br]Attention, everyone.

00:08:37.07,00:08:38.71
- The punch has been spiked![br]- [ All Gasping ]

00:08:39.11,00:08:41.86
Don't worry. Your parents have been called[br]and will be here to pick you up shortly!

00:08:42.35,00:08:43.68
[ All ][br]Yea!

00:08:44.02,00:08:46.49
Marge, someone squeezed[br]all the life out of these kids.

00:08:47.00,00:08:48.79
And unless movies and TV[br]have lied to me...

00:08:49.28,00:08:51.16
it's a crusty, bitter, old dean.

00:08:51.68,00:08:54.49
Hi there. Hello. I'm Dean Peterson,[br]but you can call me Bobby.

00:08:55.00,00:08:58.37
I just want you to know, if you ever feel[br]stressed out from studying or whatever...

00:08:58.86,00:09:00.73
I'm always up[br]for some Hacky Sack.

00:09:01.14,00:09:04.73
Or if you just want to come by and jam,[br]I used to be the bass player for the Pretenders.

00:09:05.85,00:09:07.55
" [ Fast Riff]

00:09:07.97,00:09:11.11
Boy, I can't wait to take some of[br]the starch out of that stuffed shirt.

00:09:13.63,00:09:16.57
Good morning[br]and welcome to Nuclear Physics 1 01 .

00:09:16.93,00:09:20.46
I see a lot of new faces,[br]but you know the old saying--

00:09:20.92,00:09:23.59
''Out with the old, in with the nucleus.''

00:09:25.39,00:09:27.26
Now we'll begin by--[br]Oops.

00:09:27.65,00:09:31.30
[ Laughing Loudly ]

00:09:32.24,00:09:33.56
Ah, did you see that jerk?

00:09:34.10,00:09:36.45
[ Laughing Continues ]

00:09:36.87,00:09:37.68
Dropped his notes!

00:09:38.48,00:09:41.39
[ Laughing More Loudly ]

00:09:42.61,00:09:45.32
This proton accelerator[br]destabilizes the atom...

00:09:45.80,00:09:47.86
in this chamber here,[br]then propels it--

00:09:48.31,00:09:50.20
Uh, excuse me,[br]Professor Brainiac...

00:09:50.76,00:09:53.54
but I worked in a nuclear power plant[br]for 1 0 years...

00:09:54.07,00:09:57.53
and, uh, I think I know[br]how a proton accelerator works.

00:09:57.96,00:10:01.24
- Well, please come down and show us.[br]- All right. I will.

00:10:01.24,00:10:03.67
[ Screaming ]

00:10:05.51,00:10:06.97
- In there, guys.[br]- [ Both ] Thanks, Homer.

00:10:08.48,00:10:10.26
Homer, no one blames you[br]for the accident.

00:10:10.67,00:10:13.91
We simply feel you might benefit[br]with a little outside tutoring.

00:10:14.25,00:10:15.97
I researched these names myself.

00:10:16.90,00:10:18.95
Yeah, you won this round, Dean...

00:10:19.45,00:10:21.31
but the war isn't over.

00:10:22.88,00:10:24.01
- [ Rings ][br]- Hello.

00:10:24.74,00:10:26.72
[ Homer][br]Hello, Dean. You're a stupid-head!

00:10:27.09,00:10:28.48
- Homer, is that you?[br]- [ Yelps ]

00:10:34.71,00:10:35.79
Hiya, gang.

00:10:36.42,00:10:38.90
- Intruder alert. Intruder alert.[br]- Stop the humanoid.

00:10:39.36,00:10:41.04
[ Chortling ]

00:10:41.57,00:10:43.44
Look, I'm supposed to[br]get a physics tutor.

00:10:44.17,00:10:47.41
You've come to the right place.[br]If there's one thing we know, it is science.

00:10:47.82,00:10:50.57
- And math.[br]- And the words to every Monty Python routine.

00:10:51.01,00:10:53.67
We are the knights who say ''Ni!''

00:10:54.06,00:10:56.57
Ni! Ni! Ni![br][ Giggling ]

00:10:57.07,00:10:58.20
[ Chuckles ][br]Ni.

00:10:59.71,00:11:02.28
We played Dungeons and Dragons[br]for three hours.

00:11:02.75,00:11:04.39
Then I was slain by an elf.

00:11:04.64,00:11:06.83
Listen to yourself, man.[br]You're hangin' with nerds.

00:11:07.33,00:11:09.19
- You take that back![br]- Homer, please.

00:11:09.52,00:11:11.74
These boys sound very nice,[br]but they're clearly nerds.

00:11:11.95,00:11:14.39
Really? But nerds[br]are my mortal enemy.

00:11:14.79,00:11:18.28
Dad, nerds are nothing to fear. In fact,[br]they've done some pretty memorable things.

00:11:18.74,00:11:22.58
Some nerds of note include[br]popcorn magnate Orville Redenbacher...

00:11:22.95,00:11:26.21
rock star David Byrne[br]and Supreme Court Justice David Souter.

00:11:26.66,00:11:28.69
[ Gasps ][br]Oh, not Souter!

00:11:29.60,00:11:30.64
Oh, no!

00:11:32.58,00:11:33.48
Come on, Mr. Simpson.

00:11:33.84,00:11:36.27
You'll never pass this course[br]if you don't know the periodic table.

00:11:36.97,00:11:38.57
- I'll write it on my hand.[br]- Oh!

00:11:39.07,00:11:41.76
Including all known[br]lanthanides and actinides?

00:11:42.18,00:11:44.36
- [ Chuckling ] Good luck.[br]- [ All Chuckling ]

00:11:45.68,00:11:47.17
Come on, guys.

00:11:47.49,00:11:49.94
Look at yourselves![br]All you do is study.

00:11:50.37,00:11:53.37
I'm gonna show you[br]the true meaning of college.

00:11:53.99,00:11:56.50
We're gonna go out and par-ty!

00:11:56.63,00:11:58.17
Wait a minute.[br]I'll put on my snow pants.

00:11:58.52,00:11:59.60
- Me too.[br]- Me too.

00:12:00.56,00:12:02.00
Ah, the college road trip.

00:12:02.45,00:12:04.72
What better way to spread[br]beer-fueled mayhem?

00:12:05.46,00:12:07.58
If you're going for a ride,[br]I'd like you to take Bart and Lisa.

00:12:07.93,00:12:11.26
But, Marge, we're college guys,[br]and we're up to no good.

00:12:12.25,00:12:14.23
Mr. Simpson,[br]Gary spilled his ear medicine.

00:12:17.04,00:12:18.80
Oh, those baby ducks[br]were so cute.

00:12:19.27,00:12:21.37
I can't believe they let us[br]walk right up and feed them.

00:12:21.90,00:12:24.19
- I need to go to the bathroom.[br]- We stopped five minutes ago.

00:12:24.55,00:12:26.29
Someone knocked on the door,[br]and I couldn't go.

00:12:27.30,00:12:31.59
I'm telling you. A big, crazy prank[br]is just what the doctor ordered.

00:12:32.11,00:12:34.46
[ Giggling ][br]The dean will go nuts.

00:12:35.14,00:12:35.97
I got it!

00:12:36.77,00:12:39.92
We wait by his mailbox,[br]and when he comes outside...

00:12:40.73,00:12:43.32
we roll him up in a carpet[br]and throw him off a bridge!

00:12:47.31,00:12:50.69
-[ Scraping Sound ][br]- [ All Groaning ]

00:12:51.97,00:12:53.90
So it's a prank[br]you're looking for, is it?

00:12:54.73,00:12:56.42
I'll give you your prank.

00:12:57.62,00:13:00.42
The only other college in 50 miles[br]is Springfield A&M...

00:13:00.88,00:13:01.97
so they're our best target.

00:13:02.85,00:13:04.99
- Those bastards.[br]- Meet Sir Oinkcelot...

00:13:05.58,00:13:07.45
the beloved mascot[br]of Springfield A&M.

00:13:08.14,00:13:09.96
Here he is presiding[br]over last year's homecoming.

00:13:10.46,00:13:13.24
Here he is conferring[br]an honorary degree on Richard Nixon.

00:13:13.77,00:13:15.93
And here he is rolling in his own filth.

00:13:16.92,00:13:20.71
Gentlemen, I propose[br]we kidnap Sir Oinkcelot.

00:13:21.10,00:13:23.45
And then we roll him up in a carpet[br]and throw him off a bridge!

00:13:24.68,00:13:27.07
[ Laughing ][br]What?

00:13:34.20,00:13:36.84
- [ Squeals ][br]- Look, you pull its tail straight...

00:13:37.26,00:13:38.70
and it curls right back up again.

00:13:38.95,00:13:41.31
Curly, straight.[br]Curly, straight.

00:13:41.84,00:13:44.01
- Curly, straight. Curly, straight.[br]- [ Squealing ]

00:13:45.06,00:13:46.99
Mr. Simpson,[br]I don't think he likes that.

00:13:47.52,00:13:50.77
[ Giggles ] Of course he does.[br]He's a cute little piggy.

00:13:51.20,00:13:54.01
Curly, straight.[br]Curly, straight. Ow!

00:13:54.68,00:13:58.49
- Why, you little--[br]- Mr. Simpson, stop!

00:13:58.97,00:13:59.90
- It's a defenseless animal![br]- [ Screams ]

00:14:02.39,00:14:06.29
- The pig's acting kinda funny.[br]- He and Mr. Simpson split a case of malt liquor.

00:14:06.76,00:14:08.26
Guys, he's really sick.

00:14:09.74,00:14:12.15
Hello![br]That sounds like a pig fainting.

00:14:15.83,00:14:16.89
[ Squealing ]

00:14:18.02,00:14:19.26
I'm sorry, boys.

00:14:19.63,00:14:23.84
I-I've never expelled anyone before,[br]but that pig had some powerful friends.

00:14:24.25,00:14:26.73
Oh, you'll pay.[br]Don't think you won't pay!

00:14:30.38,00:14:33.38
Guys, believe me.[br]I didn't mean to get you expelled.

00:14:33.83,00:14:36.64
Don't worry, Mr. Simpson.[br]We can take care of ourselves.

00:14:38.45,00:14:39.92
Ah, wallet inspector.

00:14:40.51,00:14:42.96
Oh, here you go.[br]I believe that's all in order.

00:14:43.71,00:14:45.22
I can't believe that worked!

00:14:46.25,00:14:49.33
Hey! That's not[br]the wallet inspector.

00:14:55.95,00:14:57.95
Marge, they don't have[br]anywhere to stay.

00:14:58.44,00:15:00.63
And they're geniuses.[br]They'll solve all our problems.

00:15:01.19,00:15:03.95
They'll elevate us to the status[br]of kings on Earth!

00:15:04.51,00:15:08.53
- Mr. Simpson, we all have nosebleeds.[br]- Oh, for the love of--

00:15:11.59,00:15:13.65
- [ Loud Beeping ][br]- [ Groans ]

00:15:14.02,00:15:16.42
What's wrong with this phone?[br]It's making crazy noises.

00:15:16.90,00:15:19.44
Those crazy noises[br]are computer signals.

00:15:20.29,00:15:24.30
Some guys at M.I.T. are sending us reasons[br]why Captain Picard is better than Captain Kirk.

00:15:24.80,00:15:27.51
- Ha! They're out of their minds.[br]- [ Groans ]

00:15:31.24,00:15:35.22
Oh, I heard about this. This is the one[br]where Scratchy finally gets Itchy.

00:15:35.66,00:15:36.97
Wow!

00:15:38.88,00:15:39.87
[ Cackling ]

00:15:54.47,00:15:55.28
[ Whistles ]

00:16:03.03,00:16:05.70
My purpose in life[br]is to witness this moment.

00:16:10.64,00:16:12.67
- [ Screaming ][br]- We need the outlet for our rock tumbler.

00:16:13.11,00:16:15.56
- Plug it in! Plug it in![br]- What, the rock tumbler or the TV?

00:16:16.13,00:16:17.82
The TV! The TV!

00:16:19.41,00:16:22.11
-"Show "[br]- [ Cheering ]

00:16:22.62,00:16:27.05
Wow! They'll never let us show that again,[br]not in a million years!

00:16:27.58,00:16:29.35
[ Chortling ]

00:16:29.96,00:16:30.70
[ Screaming ]

00:16:31.75,00:16:34.38
Dad, start digging[br]some nerd holes.

00:16:35.01,00:16:38.47
It's bad enough they put their retainers[br]in the dishwasher. Can't we do something?

00:16:39.08,00:16:42.63
Look, I'm sure we can work something out[br]where we can all live in harmony.

00:16:43.12,00:16:45.66
- Right, Marge?[br]- No, I want those geeks out of my house.

00:16:46.91,00:16:48.86
You really think you can[br]get us back into college?

00:16:49.18,00:16:50.38
Absolutely.

00:16:50.72,00:16:52.83
Now, the only antidote[br]to a zany scheme...

00:16:53.24,00:16:54.92
is an even zanier scheme!

00:16:55.49,00:16:56.98
Why does it have to be zany?

00:16:57.56,00:16:58.89
[ Gasps ][br]I've got it!

00:16:59.74,00:17:02.53
We're gonna fix it[br]so you guys save the dean's life.

00:17:05.47,00:17:06.38
-[ Engine Rewing ][br]- Perfect.

00:17:07.80,00:17:09.42
[ Tires Screeching ]

00:17:09.98,00:17:11.78
" [ Whistling ]

00:17:12.96,00:17:16.09
Okay, guys. We push him out of the way[br]in exactly three seconds.

00:17:16.47,00:17:17.93
Should we correct[br]for wind resistance?

00:17:18.74,00:17:19.70
Hmm, possibly.[br]What do you think?

00:17:20.71,00:17:22.37
-[ Thudding ][br]- Oh, my.

00:17:23.70,00:17:26.73
Well, Dean, I'm really sorry[br]for the running-you-over prank.

00:17:27.15,00:17:30.27
- Prank?[br]- And all those other pranks were my idea too.

00:17:30.98,00:17:32.54
I'm the one who should be expelled.

00:17:33.80,00:17:34.83
Well, I'm touched by your honesty.

00:17:35.23,00:17:38.31
And who knows--[br]Perhaps I've been a bit of an ogre myself.

00:17:38.83,00:17:40.30
- Yes, you have.[br]- How's this?

00:17:40.63,00:17:42.13
I'll readmit your friends...

00:17:42.49,00:17:44.84
and we'll forget[br]this whole silly incident ever occurred.

00:17:45.50,00:17:48.21
Oh, Dean. This is what[br]your new hip is going to look like.

00:17:48.98,00:17:52.63
[ Nervous Chuckling ][br]You're gonna have to go easy on it.

00:17:53.93,00:17:56.05
Oh, it's good to be back[br]after all these weeks.

00:17:56.62,00:17:58.23
Better check our answering machine.

00:17:59.07,00:18:01.26
[ Woman's Voice ][br]Number of messages received: zero.

00:18:01.73,00:18:05.10
- [ All Sighing ][br]- We really want to thank you, Mr. Simpson.

00:18:05.78,00:18:07.25
Ah, no problem, guys.

00:18:07.62,00:18:11.11
The important thing is[br]that we wrapped up all the loose ends.

00:18:13.04,00:18:16.96
So, in conclusion, good luck[br]on tomorrow's big final exam.

00:18:17.41,00:18:18.99
Exam? Oh!

00:18:19.42,00:18:21.35
This is just like one of those bad dreams![br][ Screams ]

00:18:23.08,00:18:25.06
What are you gonna do, Mr. Simpson?

00:18:25.43,00:18:27.11
Actually,[br]I've been working on a plan.

00:18:27.53,00:18:29.51
During the exam,[br]I'll hide under some coats...

00:18:29.99,00:18:32.43
and hope that somehow[br]everything will work out.

00:18:33.10,00:18:37.64
Or with our help, you can cram[br]like you've never crammed before!

00:18:38.10,00:18:39.31
Whatever.[br]Either way is good.

00:18:55.39,00:18:56.46
Whoo-hoo!

00:19:00.54,00:19:02.65
Oh, man.[br]I can't believe you failed.

00:19:03.21,00:19:07.50
Oh, I'm gonna lose my job[br]just 'cause I'm dangerously unqualified!

00:19:08.03,00:19:09.45
Mr. Simpson, there is a way.

00:19:09.86,00:19:12.77
We could, well, use a computer[br]to change your grade.

00:19:13.21,00:19:14.83
[ Gasps ][br]Computers can do that?

00:19:15.24,00:19:18.19
Oh, yes. The only problem is[br]the moral dilemma it raises, which requires--

00:19:18.67,00:19:21.75
[ Kissing ][br]Oh, I love-- Moral whuzzah?

00:19:23.04,00:19:24.96
An A-plus![br]How did you do it?

00:19:25.49,00:19:29.94
Oh, let's just say I had help[br]from a little magic box.

00:19:30.36,00:19:32.21
- You changed your grade with a computer?[br]- D'oh!

00:19:32.93,00:19:34.05
Way to go, Dad!

00:19:34.39,00:19:36.73
The important thing is[br]that we all learned a lesson.

00:19:37.78,00:19:41.88
These guys learned the richness and variety[br]of the world outside college.

00:19:42.37,00:19:43.55
- No, we didn't.[br]- Oh.

00:19:43.98,00:19:48.17
Then I learned the real value of college[br]is to study and work hard.

00:19:48.56,00:19:53.39
No, you didn't. You only passed your course by[br]cheating, which you always taught us was wrong.

00:19:53.93,00:19:55.35
Hmm. True.

00:19:55.56,00:19:58.34
And I learned that in order for you[br]to set a good example for your son...

00:19:58.77,00:20:01.12
you're gonna take that course over again[br]without cheating.

00:20:01.58,00:20:04.61
Oh, Marge! You're worse[br]than that crusty old dean.

00:20:05.44,00:20:08.74
[ Sighs ][br]Well, I guess it's back to college for me.

00:20:09.31,00:20:12.24
That means it's time to--[br]What did I teach you guys?

00:20:13.12,00:20:14.55
[ Nerds ][br]Par-ty down?

00:20:15.14,00:20:16.31
Yes!

00:20:16.82,00:20:18.70
"[ Rock ]

00:21:07.06,00:21:08.59
- [ People Chattering ][br]- Shh!

