[INFORMATION]
[TITLE]
[AUTHOR]
[SOURCE]
[PRG]
[FILEPATH]
[DELAY]0
[CD TRACK]0
[COMMENT]
[END INFORMATION]
[SUBTITLE]
[COLF]&HFFFFFF,[STYLE]bd,[SIZE]24,[FONT]Tahoma
00:00:02.29,00:00:05.05
[ Chorus ][br]" The Simpsons "

00:00:05.72,00:00:06.57
[ Tires Screeching ]

00:00:08.66,00:00:10.39
D'oh! [ Screams ]

00:00:23.98,00:00:26.37
Well, sir, it has been an[br]uneventful week in Badger Falls...

00:00:28.22,00:00:31.80
where the women are robust,[br]the men are pink-cheeked...

00:00:32.80,00:00:35.59
and the children are[br]pink-cheeked and robust.

00:00:36.00,00:00:37.32
[ Laughing ]

00:00:40.07,00:00:41.61
What the hell's so funny?

00:00:42.90,00:00:45.01
[ Inhales ][br]At the Apple Biscuit Café...

00:00:45.52,00:00:47.84
where the smiles are free,[br]don't you know...

00:00:48.43,00:00:50.39
Sven Inqvist studied the menu.

00:00:50.84,00:00:54.21
Finally, he ordered the same[br]thing he has every day.

00:00:54.72,00:00:56.55
[ Laughter]

00:00:58.10,00:01:03.00
- Maybe it's the TV.[br]- Stupid TV. Be more funny! [ Grunts ]

00:01:04.33,00:01:07.06
Well, sir, I think it is time[br]to turn this pledge drive...

00:01:07.42,00:01:09.14
over to Troy McClure.

00:01:09.14,00:01:12.14
I can't keep up this pace forever.

00:01:12.51,00:01:14.21
[ Deep Sigh ]

00:01:14.56,00:01:17.62
Hi, I'm Troy McClure. You might remember me[br]from such telethons as...

00:01:18.16,00:01:21.48
''Out with Gout '88'' and ''Let's Save[br]Tony Orlando's House.''

00:01:21.91,00:01:23.58
Folks, do you realize[br]without your support...

00:01:24.02,00:01:27.01
public television can't afford to bring you[br]such award-winning shows as...

00:01:27.35,00:01:28.66
Edward the Penitent?

00:01:28.97,00:01:31.10
I'm really, really, really sorry.

00:01:31.44,00:01:33.81
I'm afraid sorry doesn't[br]cut it with this pope.

00:01:34.16,00:01:35.97
- Oh-ho.[br]-[ Phone Ringing ]

00:01:36.27,00:01:38.41
What the hell? Oh, we got a call.

00:01:38.76,00:01:41.14
[ Chuckles ][br]Some idiot actually called in.

00:01:41.44,00:01:43.35
- Hello. What's your name?[br]- Marge Simpson.

00:01:43.67,00:01:47.89
- [ Screams ][br]- I'd like to pledge $30. Oh, thank you.

00:01:48.22,00:01:51.78
Marge, it's public TV.[br]They never have anything good.

00:01:52.15,00:01:55.18
Where are the Geraldos?[br]Where are the Eubankses-ses?

00:01:55.61,00:01:58.50
They need our support. Besides, they gave me[br]two tickets to the ballet.

00:01:58.85,00:02:02.06
- The ballet? Whoo-hoo![br]- You like ballet?

00:02:02.35,00:02:06.87
Marjorie, please. I enjoy all the meats[br]of our cultural stew.

00:02:07.26,00:02:09.39
Ahh, ballet.

00:02:09.78,00:02:13.04
Hee-hee-hee. All right.[br]Whoo-hoo! Yea!

00:02:13.39,00:02:15.59
[ Laughing ][br]Yeah!

00:02:16.16,00:02:18.83
" [ Humming With Calliope Music ]

00:02:19.28,00:02:22.12
" [ Continues ]

00:02:23.67,00:02:26.17
- [ Doorbell Rings ][br]- "[ Humming Continues ]

00:02:26.52,00:02:28.54
- Hello, Ruth.[br]- Hi, Marge.

00:02:28.82,00:02:31.18
I was wondering if you had[br]a power sander I could borrow.

00:02:31.49,00:02:32.85
- Homer?[br]- Nope.

00:02:33.23,00:02:35.17
- [ Whirring ][br]- That's one right there.

00:02:35.52,00:02:37.79
All right. But, remember, it's mine.

00:02:43.20,00:02:45.84
That's what ballet is?[br][ Groans ]

00:02:46.23,00:02:49.13
You promised. You can't back out[br]like when you volunteered...

00:02:49.45,00:02:52.19
for that army experiment[br]to avoid dinner at my sisters'.

00:02:53.66,00:02:56.13
Mr. Simpson, you do realize[br]this may result in...

00:02:56.52,00:02:58.35
hair loss, giddiness[br]and the loss of equilibrium?

00:02:58.71,00:03:00.51
Yeah, yeah, yeah.[br]Just give me the serum.

00:03:01.97,00:03:04.77
[ Chuckles ][br]It was worth it.

00:03:05.70,00:03:09.52
- [ Body Thuds On Floor ][br]- [ Homer Giggling ]

00:03:12.02,00:03:14.71
- Hey, Homer,[br]you wanna get a beer on the way home?[br]- I can't.

00:03:15.08,00:03:16.83
I gotta take my wife to the ballet.

00:03:17.24,00:03:19.77
[ Chuckles ] Gonna go see the bear[br]in the little car, huh?

00:03:20.13,00:03:21.63
Hmm?

00:03:22.69,00:03:25.55
Mmm, invisible cola.

00:03:28.03,00:03:31.98
Mmm. [ Short Laugh ][br]Time to stick it to the man.

00:03:32.37,00:03:35.28
Hey, hey. Careful there, Homer. I heard[br]somebody lost an arm in there once.

00:03:35.76,00:03:37.81
[ Scoffs ][br]That's just an old wives' tale.

00:03:38.81,00:03:42.20
[ Grunting, Straining ]

00:03:43.22,00:03:45.82
[ Grunting ]

00:03:46.17,00:03:47.69
Just a little more--

00:03:48.53,00:03:49.64
[ Grunts ]

00:03:49.93,00:03:51.29
Got it.[br][ Screams ]

00:03:51.78,00:03:53.38
I'm stuck. Help me.

00:03:53.38,00:03:55.32
- He's done for![br]- Let's get outta here!

00:03:55.32,00:03:56.26
[ Both Yelling ]

00:03:57.67,00:03:59.01
[ Grunting ]

00:04:01.88,00:04:04.66
[ Grunts ][br]Must... get... to ballet.

00:04:05.26,00:04:07.96
Promised Marge.[br][ Grunts ]

00:04:08.91,00:04:11.37
Hello? Can I get some help?

00:04:12.47,00:04:14.77
Snack-related mishap.

00:04:16.06,00:04:18.35
[ Grunting ]

00:04:20.21,00:04:22.49
Mmm. Candy.

00:04:23.95,00:04:25.96
- [ Rings ][br]- Hello?

00:04:26.41,00:04:28.80
Marge, this may be[br]hard to believe...

00:04:29.07,00:04:31.66
but I'm trapped inside[br]two vending machines.

00:04:32.05,00:04:34.27
[ Loud Sigh ][br]Sure, Homer.

00:04:34.60,00:04:36.27
Trapped in vending machines. Okay.

00:04:37.53,00:04:39.71
Would you two[br]like to go to the ballet?

00:04:40.07,00:04:42.21
- [ Snorts ] That's girl stuff.[br]-[ Doorbell Rings ]

00:04:42.69,00:04:46.34
Thanks, Marge. When my husband left,[br]he took all our power tools...

00:04:46.71,00:04:49.79
along with the car,[br]my youth, my faith in mankind.

00:04:50.27,00:04:51.87
Well, see ya.

00:04:54.12,00:04:55.64
Mmm. Hey, wait!

00:04:58.50,00:05:00.33
"[ Classical ]

00:05:03.91,00:05:06.90
"[ Continues ]

00:05:08.60,00:05:12.53
- Vyachepov's loins oughta be outlawed.[br]- [ Giggling ]

00:05:14.10,00:05:17.68
[ Scoffs ] Far too much dancing,[br]not nearly enough prancing.

00:05:18.09,00:05:19.99
A little mincing would be nice.

00:05:24.04,00:05:25.05
[ All Gasp ]

00:05:26.79,00:05:29.04
- [ Shattering ][br]-[ Buzzer Buzzes ]

00:05:29.44,00:05:30.48
[ Applause ]

00:05:30.87,00:05:32.83
Well, thank you for a lovely time.

00:05:33.15,00:05:35.86
- You're not going home already, are you?[br]- It's almost 9:30.

00:05:36.18,00:05:39.13
[ Laughs ] Yeah, right.[br]We better turn in.

00:05:40.89,00:05:43.34
[ Laughs, Stops ][br]Oh, you were serious.

00:05:45.06,00:05:46.97
Homer, this-this is never easy to say.

00:05:47.37,00:05:49.08
I'm gonna have to saw your arms off.

00:05:49.39,00:05:51.75
- They'll grow back, right?[br]- Oh, yeah.

00:05:52.18,00:05:54.05
- Whew.[br]- [ Whirring ]

00:05:54.55,00:05:56.35
Homer, are you just[br]holding on to the can?

00:05:56.76,00:05:59.48
- Your point being?[br]-[ Men Laughing ]

00:06:06.36,00:06:08.39
- I envy you and Homer.[br]- Thank you.

00:06:10.32,00:06:13.94
- Why?[br]- If you ever met my ex-husband, you'd understand.

00:06:13.82,00:06:16.87
All he ever did was eat, sleep[br]and drink beer.

00:06:17.28,00:06:19.98
- Your point being?[br]- And to top it off, he's been stiffing me...

00:06:20.28,00:06:22.26
on child support[br]for the last four months.

00:06:22.65,00:06:24.71
[ Groans ][br]Well, you were unlucky.

00:06:25.02,00:06:26.84
But there are[br]a lot of good men out there.

00:06:27.14,00:06:29.49
Hey, can I throw up in your bathroom?

00:06:29.89,00:06:32.18
- I'll buy something.[br]- [ Shudders ]

00:06:36.27,00:06:39.23
Marge, I know you didn't believe me[br]about the vending machines.

00:06:39.52,00:06:42.71
That's why I had[br]the firemen write me a note.

00:06:43.81,00:06:48.44
''Mrs. Simpson: While we were rescuing[br]your husband, a lumberyard burned down.''

00:06:48.78,00:06:51.14
D'oh! Lumber has a million uses.

00:06:51.62,00:06:53.93
I'm disappointed in you,[br]but it turns out...

00:06:54.26,00:06:56.46
I had a wonderful time[br]with Ruth Powers.

00:06:56.74,00:06:58.25
In fact, we're going out again[br]tomorrow night.

00:06:58.57,00:07:01.94
Marge, that's twice. I think you're spending[br]entirely too much time with this woman.

00:07:02.24,00:07:04.90
Homer, please. You know it's hard[br]for me to make friends.

00:07:05.07,00:07:09.26
Marge, you can't go out on Saturday.[br]That's our special night.

00:07:09.66,00:07:13.30
- What's so special about it?[br]- What's so-- Oh, I don't know.

00:07:13.61,00:07:17.99
- A little show called[br]Dr. Quinn, Medicine Woman?[br]- [ Groans ]

00:07:20.76,00:07:22.45
- Where're you going?[br]- I don't know.

00:07:22.78,00:07:24.69
- When will you be home?[br]- I'm not sure.

00:07:24.94,00:07:26.81
- Where're you going?[br]- You already asked me that.

00:07:27.06,00:07:28.88
- Will you bring me back something?[br]- [ Horn Honks ]

00:07:29.29,00:07:31.28
Don't wait up.

00:07:34.78,00:07:38.81
How can you do this, Marge?[br]How can you desert your children?

00:07:39.20,00:07:41.37
- Have a blast, Mom.[br]- Rock the Casbah.

00:07:41.77,00:07:43.60
Man's best friend indeed.

00:07:44.18,00:07:45.56
Whoa.

00:07:46.96,00:07:49.08
You look... nice.

00:07:49.39,00:07:52.08
Tonight has nothing to do with nice.[br]Tonight's all about--

00:07:52.90,00:07:56.39
"Sunshine, lollipops[br]and rainbows ev--"

00:07:56.90,00:07:58.56
Oh. Sorry, Marge.[br]Wrong tape.

00:07:58.97,00:08:01.96
" Welcome to thejungle[br]We got fun and games "

00:08:02.33,00:08:04.74
- "We got everything-- "[br]- [ Marge Screams ]

00:08:07.23,00:08:09.58
I can't believe your mother went out[br]to have fun without me.

00:08:10.04,00:08:13.57
Don't worry. You'll feel better[br]once we put your hair up in curlers...

00:08:13.88,00:08:15.56
and give you a makeover, Homina.

00:08:15.92,00:08:18.33
[ High-pitched Voice ] Oh, that would be delight--[br][ Normal Voice ] Quiet, boy.

00:08:18.61,00:08:21.97
There's nothing to feel ashamed of here.[br]Women have a right to a night out. Right, Lisa?

00:08:22.45,00:08:24.86
Sure, Dad.[br][ Imitates Whip Cracking ]

00:08:25.20,00:08:27.14
That's it! I'm calling my buddies.

00:08:27.43,00:08:29.92
Marge is not the only one[br]who can have a girls' night out.

00:08:30.31,00:08:32.68
Oh, no can do, Homer.[br]I'm watching the game.

00:08:34.98,00:08:36.55
Shave up not down, you idiot.

00:08:36.89,00:08:40.42
Ooh, sounds delish.[br]Let me just toss some jeans on and--

00:08:40.80,00:08:42.28
Wait a minute. Who is this?

00:08:42.64,00:08:44.31
- [ Ringing ][br]- Well, howdilly dodilly-do.

00:08:44.77,00:08:47.06
- [ Line Clicks, Dial Tone ][br]- Hello?

00:08:47.33,00:08:49.40
Hello? Hellodilly-odilly?

00:08:49.72,00:08:52.30
Fine. I can have[br]a great time all by myself.

00:08:52.72,00:08:56.13
Hey, Dad, I think state and federal laws[br]require us to have a babysitter.

00:08:56.43,00:08:58.98
Oh, Lisa. Haven't you seen Home Alone?

00:08:59.32,00:09:03.51
If some burglars come, it'll be a[br]very humorous and entertaining situation.

00:09:03.89,00:09:07.80
You're absolutely right, Homer.[br]We don't need a babysitter.

00:09:08.29,00:09:10.60
Wait a second. Mmm.

00:09:12.30,00:09:14.78
You kids do need a babysitter.

00:09:15.12,00:09:19.46
Blast that infernal card.[br]Don't give that card to me.

00:09:19.83,00:09:22.01
- Here you go-- No![br]- [ Doorbell Rings ]

00:09:22.54,00:09:26.01
Mr. Simpson, I was just[br]going through your garbage...

00:09:26.31,00:09:29.17
and I couldn't help overhearing that[br]you need a babysitter.

00:09:29.59,00:09:31.74
Of course, being[br]a highly skilled attorney...

00:09:32.09,00:09:36.48
- my fee is $1 7 5 an hour.[br]- We pay eight dollars for the night...

00:09:36.80,00:09:39.09
- and you can take two Popsicles out of the freezer.[br]- Three.

00:09:39.44,00:09:41.90
- Two.[br]- Okay, two, and I get to keep this old birdcage.

00:09:42.20,00:09:44.38
- Done.[br]- Still got it.

00:09:45.40,00:09:47.72
[ Marge ][br]Oh, I've heard a lot about Shot Kickers.

00:09:48.85,00:09:51.43
" [ Country ]

00:09:54.80,00:09:57.11
[ Grunts ] How come no one else's[br]chair is doing this?

00:09:58.69,00:10:00.86
Hey, baby. Feel like getting lucky?

00:10:01.26,00:10:06.69
I am lucky. I have a husband and three[br]wonderful children. Thank you very much.

00:10:08.06,00:10:10.75
Sometimes you gotta go[br]where everybody knows your name.

00:10:11.21,00:10:13.65
- Hey, guys![br]- [ Fan Squeaking ]

00:10:15.58,00:10:16.94
[ Squeaking ]

00:10:17.30,00:10:18.91
- Moe, get the darts. I wanna play.[br]- No.

00:10:19.46,00:10:23.26
- We're phasing out the games.[br]People drink less when they're having fun.[br]- Oh.

00:10:24.68,00:10:27.41
- What was it you wanted to show me?[br]- This.

00:10:27.81,00:10:30.54
[ Gasps ] You're not gonna hunt me[br]for sport are you?

00:10:31.12,00:10:34.37
[ Chuckles ] Relax, Marge. I'd never turn[br]a gun on a human being.

00:10:34.77,00:10:37.28
My husband, on the other hand.

00:10:39.33,00:10:41.72
- Come on. You try it.[br]- No. I couldn't.

00:10:42.04,00:10:44.29
Yeah.Just breathe slowly[br]and squeeze the--

00:10:46.92,00:10:48.84
I hit it! I hit it!

00:10:49.26,00:10:53.96
My cans. My precious, antique cans.[br]Aw, look what you done to 'em.

00:10:54.62,00:10:57.21
Well, it's getting late.[br]Maybe we should call it a night.

00:10:57.75,00:11:00.12
It's only midnight.[br]Come on. I know a place.

00:11:03.40,00:11:04.98
- Whoa.[br]- Beautiful, huh?

00:11:05.35,00:11:07.42
Homer and I used to[br]come up here on dates.

00:11:10.69,00:11:13.39
Homer, stop that.[br]It's just a weather station.

00:11:13.82,00:11:17.16
[ Grunts ] Come on, Marge.[br]It's fun to smash things.

00:11:18.35,00:11:20.20
[ Laughs ][br]I smashed it good.

00:11:21.75,00:11:24.00
You got real ''purdy'' hair.

00:11:24.50,00:11:26.54
You know, Marge,[br]of all the places we've been tonight...

00:11:26.97,00:11:29.99
- I think I like this one the best.[br]- Mmm. Me too.

00:11:30.51,00:11:32.53
Look, you can see our houses.

00:11:33.20,00:11:37.20
There's an awful lot of black smoke[br]coming from my chimney.

00:11:37.71,00:11:40.44
Mr. Hutz, why are you[br]burning all your personal papers?

00:11:40.83,00:11:43.47
As of this moment,[br]Lionel Hutz no longer exists.

00:11:43.82,00:11:46.52
Say hello to Miguel Sanchez.

00:11:47.38,00:11:49.01
Mmm, maybe we should[br]call it a night.

00:11:49.37,00:11:53.89
Okay. I should get home to my daughter[br]before that naked talk show comes on.

00:11:54.08,00:11:55.61
[ Starts Engine ]

00:11:56.09,00:11:57.92
Ah, young love.

00:12:00.86,00:12:02.86
The old make-out place.

00:12:04.57,00:12:06.47
Hey, a new weather station!

00:12:07.34,00:12:10.10
I'll bash it good. Oh...

00:12:10.58,00:12:13.07
it's just no fun without Marge.

00:12:15.58,00:12:18.78
Ah, there's nothing like[br]moonshine from your own still.

00:12:19.16,00:12:20.87
Oh, Simpson.

00:12:21.43,00:12:25.23
- What are you doing here?[br]- My wife's having a girls' night out.

00:12:25.64,00:12:27.80
Ah,just get one of those[br]inflatable women.

00:12:28.11,00:12:29.33
But make sure it's a woman though.

00:12:29.63,00:12:31.50
'Cause one time I--[br][ Stammering ]

00:12:33.52,00:12:35.54
Come on. I'll, uh--[br]I'll give you a ride home.

00:12:38.99,00:12:41.25
[ Groans ][br]I miss you, Marge.

00:12:41.93,00:12:45.20
Huh. Their left taillight's[br]a little smaller than their right one.

00:12:45.59,00:12:47.36
- I better pull 'em over.[br]- [ Siren Wails ]

00:12:48.49,00:12:51.04
- I think they want us to stop.[br]- Fat chance.

00:12:51.55,00:12:53.89
- This car's stolen.[br]- Stolen?

00:12:54.78,00:12:56.29
- [ Revs Engine ][br]- [ Marge Screams ]

00:12:56.64,00:12:59.27
Looks like we got ourselves[br]an old-fashioned car chase.

00:13:00.59,00:13:02.04
" [ Pop ]

00:13:02.04,00:13:05.70
- "Sunshine, lollipops--"[br]- [ Singing Along ] "And rainbows, everything "

00:13:06.07,00:13:10.02
"That's wonderful is what[br]I feel when we're together "

00:13:10.47,00:13:13.81
" Brighter than a lucky penny[br]when you're near "

00:13:14.20,00:13:18.11
"The rain clouds disappear[br]dear and I feel so fine "

00:13:22.77,00:13:25.00
Ruth, is there something[br]you wanna tell me?

00:13:25.31,00:13:28.70
Remember when I said my ex-husband[br]was behind on his child support?

00:13:29.03,00:13:31.64
- Mm-hmm.[br]- Well, to even things up, I kind of stole his car.

00:13:32.04,00:13:34.97
Didn't you realize all you had to do[br]was report him to the police?

00:13:35.36,00:13:39.53
- Marge, you're the levelheaded friend I never had.[br]- [ Groans ]

00:13:41.59,00:13:43.96
We're in pursuit of two female suspects.

00:13:44.25,00:13:48.28
One is wearing a green dress, pearls[br]and has a lot of blue hair.

00:13:48.60,00:13:51.02
A lot of blue hair? [ Giggles ][br]What a freak.

00:13:52.67,00:13:54.14
- [ Car Hits Bump ][br]- Ooh!

00:13:54.63,00:13:56.26
[ Screams ][br]It's Marge!

00:13:56.73,00:14:00.52
She's become a crazed criminal just because[br]I didn't take her to the ballet.

00:14:00.87,00:14:03.19
- That's exactly how Dillinger got started.[br]- Really?

00:14:04.25,00:14:07.36
I don't wanna be a wet blanket,[br]but maybe you should give yourself up.

00:14:07.70,00:14:09.61
Marge, it's a matter of principle.

00:14:09.91,00:14:13.78
I just can't let that deadbeat win again.[br]You're with me, aren't ya?

00:14:14.09,00:14:16.88
[ Thinking ] I should say something[br]reassuring yet noncommittal.

00:14:17.25,00:14:21.34
- [ Groans ][br]- Marge, there's no reason for[br]you to get dragged into this.

00:14:21.67,00:14:23.59
Once we lose the cops, I'll let you out.

00:14:23.94,00:14:25.78
Well, I don't think[br]they're gonna be that easy to lose.

00:14:26.09,00:14:28.10
These are professional lawmen and--

00:14:28.51,00:14:33.86
Oh, my God! It just disappeared.[br]It's a ghost car!

00:14:35.14,00:14:36.59
- [ Tires Screech ][br]- [ Grunts ]

00:14:36.94,00:14:39.21
There are ghost cars[br]all over these highways, you know.

00:14:39.50,00:14:41.54
- Hold me.[br]- Only if you hold me.

00:14:42.06,00:14:44.03
- [ Coyote Howling ][br]- [ Shivering ]

00:14:47.99,00:14:52.70
- You can call a cab in there.[br]- Well, bye.

00:14:54.10,00:14:56.40
I'm sorry about all this.

00:14:56.87,00:14:59.07
But you gotta admit,[br]we did have some fun.

00:14:59.41,00:15:03.12
Yeah. Everything before[br]the high-speed chase was just lovely.

00:15:03.73,00:15:07.91
- Hey. You're a good friend, Marge.[br]- Mmm.

00:15:13.86,00:15:15.70
[ Coin Clatters ]

00:15:17.01,00:15:20.41
This cross-country flight from the law[br]would be hell if we didn't stick together.

00:15:20.76,00:15:23.01
Hey. Friends stick together.

00:15:23.31,00:15:26.68
It's amazing how through all this[br]adversity, we managed to stick together.

00:15:26.99,00:15:30.18
If there's one thing decent folk do,[br]it's stick together.

00:15:30.62,00:15:33.26
I hate it when[br]the waffles stick together.

00:15:33.64,00:15:35.79
Sticking together[br]is what good waffles do.

00:15:36.67,00:15:37.76
[ Groans ]

00:15:39.22,00:15:40.90
[ Siren Approaching ]

00:15:44.59,00:15:45.72
Thanks, kid.

00:15:47.66,00:15:49.28
Marge, what are you doing?

00:15:49.57,00:15:53.51
Ruth, I've done a lot of thinking,[br]and I really consider you a friend.

00:15:53.79,00:15:56.12
And an important part[br]of friendship is--

00:15:56.39,00:15:57.52
- [ Tires Screech ][br]- [ Marge Screams ]

00:15:58.60,00:16:00.12
- [ Siren Blaring ][br]- You stupid kid!

00:16:00.47,00:16:04.51
- You know that drives away all my business.[br]- See you tomorrow, loser.

00:16:08.65,00:16:11.04
Mmm, engine-block eggs.

00:16:11.31,00:16:13.69
If we can keep these down,[br]we'll be sitting pretty.

00:16:14.36,00:16:17.47
- That's them![br]- Quiet. I can't hear the eggs.

00:16:18.45,00:16:20.40
- [ Snoring ][br]- [ Grunts ]

00:16:20.98,00:16:23.45
Hey, it's morning,[br]and Mom and Dad aren't home yet.

00:16:23.75,00:16:26.20
Don't worry. Mr. Hutz is still here[br]to take care of us.

00:16:26.63,00:16:29.43
Don't touch my stuff!.

00:16:29.81,00:16:32.27
Hey. This isn't the Y.M.C.A.

00:16:33.00,00:16:36.63
Dispatch, this is Chief Wiggum back in[br]pursuit of the rebelling women.

00:16:36.96,00:16:39.91
- [ Man On Radio ] All right. Your current location?[br]- Oh. Uh, I'm a--

00:16:40.27,00:16:43.14
I'm on a road. Looks to be asphalt.

00:16:43.63,00:16:46.28
Um, aw, geez. Trees, shrubs.

00:16:46.65,00:16:49.66
I'm directly under[br]the Earth's sun... now.

00:16:50.83,00:16:53.10
[ Man On TV] We now interrupt[br]this program for a special bulletin.

00:16:53.68,00:16:57.07
We've just received word[br]of a high-speed desert chase.

00:16:57.36,00:17:02.24
The suspects have been identified as Ruth Powers[br]and Marge Simpson of Springfield.

00:17:02.60,00:17:04.16
- [ Gasps ][br]- Cool.

00:17:04.50,00:17:06.84
I always knew someday[br]Mom would violently rise up...

00:17:07.15,00:17:11.00
- and cast off the shackles of our male oppressors.[br]- Aw, shut your yap.

00:17:11.35,00:17:13.86
At the risk of editorializing,[br]these women are guilty...

00:17:14.60,00:17:16.94
and must be dealt with[br]in a harsh and brutal fashion.

00:17:17.31,00:17:19.54
Otherwise, their behavior[br]could incite other women...

00:17:19.84,00:17:22.04
leading to anarchy[br]of biblical proportions.

00:17:23.53,00:17:26.37
It's in Revelations, people!

00:17:30.75,00:17:33.70
Look. We're only two miles[br]from the state line.

00:17:34.39,00:17:37.45
We're gonna make it.[br]We're gonna be okay.

00:17:40.95,00:17:43.51
My God! That must be[br]every policeman in Springfield.

00:17:46.07,00:17:48.08
That's it. I give up.

00:17:48.42,00:17:50.87
A single mother[br]can't win in a man's world.

00:17:51.17,00:17:53.00
Ruth, that's a lot of hooey.

00:17:53.33,00:17:54.89
It's not over until it's over.

00:17:56.44,00:17:58.19
I'm sorry. I should've asked first.

00:17:58.49,00:18:02.28
No, Marge. You did it.[br]We really are gonna make it now.

00:18:05.86,00:18:08.83
Oh, no! They're headed right for[br]the Grand Chasm.

00:18:09.19,00:18:12.67
Oh, my God! They're gonna drive right[br]into it just to teach us men a lesson.

00:18:13.02,00:18:15.34
And it's all my fault!

00:18:16.72,00:18:19.35
Marge. Marge!

00:18:19.63,00:18:22.96
- Homer?[br]- Look, Marge.[br]I'm sorry I haven't been a better husband.

00:18:23.27,00:18:25.77
I'm sorry about the time[br]I tried to make gravy in the bathtub.

00:18:26.06,00:18:28.28
I'm sorry I used[br]your wedding dress to wax the car.

00:18:28.55,00:18:32.68
I'm sorry-- Oh, well, let's just say I'm sorry[br]for the whole marriage up to this point.

00:18:32.98,00:18:35.14
You're right.[br]I am lucky to have him.

00:18:35.43,00:18:38.77
But, please, Marge,[br]don't drive into that chasm!

00:18:39.06,00:18:40.54
[ Together][br]Chasm?

00:18:42.93,00:18:45.06
[ Homer And Chief Wiggum Screaming ]

00:18:48.28,00:18:49.29
[ Thud ]

00:18:54.05,00:18:59.25
Ha! And to think those idiot environmentalists[br]were protesting this landfill.

00:18:59.60,00:19:01.59
Solid waste. I could kiss you.

00:19:02.23,00:19:04.27
[ Loud Kiss ][br]Yech.

00:19:04.69,00:19:05.98
[ Kiss ][br]Ew.

00:19:06.38,00:19:07.69
[ Kiss ][br]Ugh.

00:19:08.19,00:19:10.72
[ Kiss ][br]Ooh, I think this was pizza.

00:19:12.16,00:19:14.95
[ Man ] Ruth Powers was tried[br]in Springfield Superior Court.

00:19:15.32,00:19:18.28
Thejudge dismissed her ex-husband's[br]auto theft charges...

00:19:18.56,00:19:20.98
and forced him to pay[br]all back child support.

00:19:21.41,00:19:24.88
Mr. Powers blamed the outcome[br]on his lawyer, one Lionel Hutz.

00:19:25.38,00:19:30.49
Lionel Hutz, a.k.a. Miguel Sanchez,[br]a.k.a. Dr. Nguyen Van Thoc...

00:19:30.98,00:19:34.04
was paid eight dollars for[br]his 3 2 hours ofbabysitting.

00:19:34.38,00:19:35.82
He was glad to get it.

00:19:36.17,00:19:40.88
Marge Simpson was charged with[br]a violation of penal code Section 6 1 8A...

00:19:41.19,00:19:44.33
wanton destruction[br]of precious antique cans.

00:19:44.68,00:19:46.97
She was ordered to pay[br]50 cents to replace the cans...

00:19:47.30,00:19:50.98
and $2,000 in punitive damages[br]and mental anguish.

00:19:51.82,00:19:54.96
Homer Simpson was remanded to[br]the custody of the United States Army...

00:19:55.31,00:19:59.52
neurochemical research center at Fort Meade,[br]Maryland for extensive testing.

00:19:59.86,00:20:01.30
Whoo-hoo!

