[INFORMATION]
[TITLE]
[AUTHOR]
[SOURCE]
[PRG]
[FILEPATH]
[DELAY]0
[CD TRACK]0
[COMMENT]
[END INFORMATION]
[SUBTITLE]
[COLF]&HFFFFFF,[STYLE]bd,[SIZE]24,[FONT]Tahoma
00:00:03.17,00:00:05.92
[ Chorus ][br]" The Simpsons "

00:00:05.92,00:00:06.98
[ Tires Screeching ]

00:00:08.75,00:00:11.36
D'oh![br][ Screams ]

00:00:26.95,00:00:30.23
The beauty of it is each parking space[br]is a mere one foot narrower--

00:00:30.59,00:00:32.42
indistinguishable to the naked eye...

00:00:32.69,00:00:35.02
but therein lies the game.

00:00:35.02,00:00:39.57
- I fear to watch, yet I cannot turn away.[br]- [ Cars Approaching ]

00:00:42.18,00:00:44.92
Blast it, woman.[br]You parked too close. Move your car!

00:00:45.26,00:00:47.77
I'm in the lines.[br]You got a problem, go tell your mama.

00:00:48.10,00:00:50.15
Oh, don't worry.[br]She'll hear about this.

00:00:51.02,00:00:52.76
- [ Horns Honking ][br]- [ Man ] I can't get out.!

00:00:53.09,00:00:55.07
- [ Woman ] I'm trapped.[br]- [ Man ] I can't breathe.!

00:00:55.52,00:00:58.52
- [ Honking Continues ][br]- [ Bart Laughing Sinisterly ]

00:00:59.79,00:01:02.97
Class, I know there's no way to prove[br]who actually did this...

00:01:03.32,00:01:06.87
and in our American democracy,[br]everyone is innocent until proven guilty.

00:01:07.26,00:01:10.87
- God bless America.[br]- But my classroom is not a democracy. Ha!

00:01:11.29,00:01:13.67
For the rest of the year,[br]Bart Simpson will be...

00:01:14.03,00:01:16.84
the first student called on[br]for every question.

00:01:17.22,00:01:19.63
- [ Gulps ][br]- Well, let's get started.

00:01:19.98,00:01:22.49
Can someone[br]pronounce this word?

00:01:24.01,00:01:26.09
Hmm? Bart?

00:01:27.74,00:01:29.90
Uh-- Um-- Hmm?

00:01:30.26,00:01:33.41
- Oh, pick me, teacher! I'm ever so smart.[br]- Uh--

00:01:33.98,00:01:38.34
It's ''photosynthesis''![br]Damn your feeble brain!

00:01:38.82,00:01:41.75
Oh, I couldn't read it.[br]The letters are all blurry.

00:01:42.10,00:01:44.76
Is it possible all your misbehavior[br]and miserable grades...

00:01:45.09,00:01:47.44
have been caused by[br]a simple vision disorder?

00:01:47.73,00:01:50.11
[ British Accent ] You mean it ain't me noggin',[br]it's me peepers?

00:01:50.37,00:01:52.18
Oh, well, that's just ''loverly.''

00:01:56.79,00:01:58.09
Watch this, guys.

00:02:01.20,00:02:02.29
Ooh!

00:02:04.27,00:02:06.23
- Uh-oh. He's done for.[br]- Don't worry.

00:02:06.51,00:02:08.24
The safety glass'll[br]protect us.

00:02:09.95,00:02:11.31
- [ All Gasp ][br]- [ Alarm Blaring ]

00:02:11.61,00:02:13.05
Run! We'll hide at my house!

00:02:13.89,00:02:14.96
[ All Shouting ]

00:02:15.95,00:02:18.25
Hey, this emergency exit[br]is painted on!

00:02:18.69,00:02:21.90
There's no way out! There's no way out![br]We're doomed! Doomed!

00:02:22.39,00:02:23.95
[ All Groaning ]

00:02:25.65,00:02:29.09
Well, sir, I won't bore you with the details[br]of our miraculous escape...

00:02:29.46,00:02:32.08
but we desperately need[br]a real emergency exit.

00:02:32.45,00:02:35.20
Why, that's a fabulous idea.[br]Anything else you'd like?

00:02:35.53,00:02:38.96
How about real lead in the radiation[br]shields? Urinal cakes, maybe?

00:02:39.36,00:02:41.08
Smithers, throw this at him.

00:02:41.55,00:02:42.55
[ Grunts ]

00:02:44.75,00:02:46.17
[ Shouting ]

00:02:46.63,00:02:48.11
Smithers, where does[br]that tube go?

00:02:48.41,00:02:50.43
I'm not sure, sir.[br]It was here when we moved in.

00:02:51.39,00:02:52.48
"[ Exotic ]

00:02:53.47,00:02:54.23
[ Shouting Continues ]

00:02:55.15,00:02:57.50
[ Men ][br]Dance! Dance! Dance! Dance!

00:02:58.02,00:02:59.73
[ Men Ululating ]

00:03:01.91,00:03:04.23
Sir, we'll need a new[br]dangerous emissions supervisor.

00:03:04.62,00:03:06.41
Yes, we'll find[br]someone cheap.

00:03:06.80,00:03:08.53
It's been a very[br]lean year for us.

00:03:09.44,00:03:10.77
[ Both ][br]Money fight!

00:03:13.56,00:03:14.80
[ Both Laughing ]

00:03:15.46,00:03:17.25
Mmm.[br][ Mumbles ]

00:03:17.58,00:03:22.13
Excellent, Zutroy. Work hard[br]and each day you'll get a shiny penny.

00:03:22.53,00:03:24.36
[ Men Shouting ]

00:03:26.15,00:03:27.52
Agent Wesson,[br]Department of Labor.

00:03:27.92,00:03:29.99
- This man's an illegal alien.[br]- [ Chuckles ]

00:03:30.28,00:03:33.36
That's preposterous.[br]Zutroy here is as American as apple pie.

00:03:33.70,00:03:35.83
[ Foreign Language ][br]Mr. Burns.

00:03:36.15,00:03:38.25
This plant violates[br]every labor law in the book.

00:03:38.55,00:03:41.89
We found a missing Brazilian soccer team[br]working in your reactor core.

00:03:42.17,00:03:44.03
That plane crashed on my property!

00:03:44.34,00:03:46.05
Look, Mr. Burns,[br]we want to see some changes.

00:03:46.35,00:03:49.94
For starters, you can reverse your sexist[br]employment policies and hire at least one woman.

00:03:50.54,00:03:52.83
All right.[br]I'll bring in a woman.

00:03:53.24,00:03:56.81
- But I still stand by my hiring policies.[br]- [ Quacking ]

00:03:57.26,00:03:58.77
Get back to work, Stewart!

00:04:02.05,00:04:05.12
Now with my new H.M.O.,[br]I can provide every medical service...

00:04:05.45,00:04:07.46
you'll ever need under one roof.

00:04:07.85,00:04:09.61
You do have insurance,[br]don't you?

00:04:10.08,00:04:12.34
- Yes.[br]- Well, that's wonderful.

00:04:13.19,00:04:14.74
[ Chuckling ][br]Let's go visit the optometrist.

00:04:17.11,00:04:19.77
Your son has a temporary[br]condition called ''lazy eye''...

00:04:20.10,00:04:22.05
where one eye[br]is weaker than the other.

00:04:22.35,00:04:24.45
- You'll have to wear these for two weeks.[br]- Oh!

00:04:24.80,00:04:26.77
Menachem Begin wore a pair[br]just like them.

00:04:27.41,00:04:29.94
Hmm. That scalp's a little dry.[br]Better see our dermatologist.

00:04:30.30,00:04:34.22
Rub a palm full of this medicated salve[br]into your scalp every half an hour.

00:04:34.63,00:04:37.07
Keep him away from open flames[br]and pregnant women.

00:04:37.57,00:04:41.18
Ah, these should help[br]those fallen arches. Enjoy.

00:04:41.72,00:04:43.33
Hmm. Throat[br]looks a little red.

00:04:43.67,00:04:45.98
- I'd better spray it.[br]- [ Coughing ]

00:04:48.22,00:04:49.82
[ Altered Voice ][br]Oh, thanks, nice lady.

00:04:50.13,00:04:52.62
My voice is crazy[br]with this spraying already.

00:04:53.12,00:04:57.60
Oy, I feel so much better,[br]Mr. Medical Science-type Person.

00:04:58.46,00:05:01.55
If they hire a woman,[br]we won't be able to spit on the floor.

00:05:01.88,00:05:03.93
And we can't take off our pants[br]when it gets real hot.

00:05:04.25,00:05:06.50
And we won't be able to pee[br]in the drinking fountain.

00:05:08.08,00:05:09.87
Yeah-- I mean, that--

00:05:10.33,00:05:13.99
You know, if we wanted to.[br]Not that I ever did.

00:05:14.51,00:05:17.60
Gentlemen, I'd like you to meet[br]your new coworker, Mindy Simmons.

00:05:18.03,00:05:19.80
I think she has a degree[br]in engineering or something.

00:05:19.80,00:05:22.10
- Hi. How's it going?[br]- Pleased to meet you.

00:05:22.48,00:05:24.50
- Yeah, ditto.[br]- Hi. Ooh.

00:05:25.29,00:05:26.33
[ Gasps ]

00:05:29.16,00:05:30.73
Homer, what's the matter?

00:05:31.09,00:05:33.91
Ain't you never seen a naked chick[br]ridin' a clam before?

00:05:35.11,00:05:36.71
Gotta go! Ahhh!

00:05:37.58,00:05:39.13
What the hell was that?

00:05:39.53,00:05:41.85
I probably shouldn't have eaten[br]that packet of powdered gravy...

00:05:42.18,00:05:44.27
I found in the parking lot.

00:05:46.35,00:05:49.36
[ Both ] Nice glasses, four eyes.[br][ Laugh ]

00:05:49.85,00:05:55.28
Yeah, nice shoes, uh,[br]two feet. Yeah.

00:05:55.65,00:05:58.92
- Your appearance is comical to me.[br]- [ Kids Laughing ]

00:06:00.24,00:06:02.14
[ Gasps ][br]I'm a nerd!

00:06:02.53,00:06:04.68
[ Gasps ][br]So am I!

00:06:06.42,00:06:09.83
Yeah. Another day,[br]another box of stolen pens.

00:06:10.15,00:06:14.23
- Have a good night, Homer.[br]- You too.

00:06:16.34,00:06:18.22
No goose bumps,[br]no hallucinations.

00:06:18.60,00:06:20.88
That last time[br]was just a fluke.

00:06:21.38,00:06:24.08
- " [ Whistling ][br]- [ Tires Screeching, Horns Honking ]

00:06:30.64,00:06:34.60
[ Fish ] Homer loves Mindy![br]Homer loves Mindy!

00:06:35.18,00:06:37.47
Hey, Homer, you're[br]hallucinating again.

00:06:37.80,00:06:39.42
Not a good sign.

00:06:42.47,00:06:45.44
So, uh, what do you guys[br]think of Mindy?

00:06:45.86,00:06:47.90
Seems okay.[br]Anybody see the game last night?

00:06:48.26,00:06:51.22
Yeah. That Mindy seems real nice.

00:06:51.56,00:06:54.09
Homer, what's with you?[br]You're talking during a coffee break.

00:06:54.42,00:06:57.48
Yeah. Usually you just take the box[br]of doughnuts into the bathroom.

00:06:58.32,00:07:00.47
Mindy has a motorcycle.

00:07:02.77,00:07:07.36
Look, everybody. I'm the same person[br]I always was. Whoa!

00:07:07.56,00:07:09.50
- [ Shouting ][br]- [ Kids Screaming ]

00:07:11.63,00:07:13.29
- [ Grunting ][br]- [ Kids Laughing ]

00:07:16.01,00:07:19.86
- Hey, he's learning on his own![br]- Get him!

00:07:20.51,00:07:21.92
[ All Grunting ]

00:07:23.01,00:07:24.98
- Moe, I need your advice.[br]- Yeah?

00:07:25.33,00:07:30.62
See, I got this friend named[br]JoeyJo-JoJunior Shabadoo.

00:07:30.99,00:07:34.05
- That's the worst name I ever heard.[br]- [ Sobbing ]

00:07:34.48,00:07:37.83
- Bye,JoeyJo-Jo![br]- Oh, what the hell? It's me.

00:07:38.36,00:07:41.35
I'm attracted to another woman.[br]What am I going to do?

00:07:41.67,00:07:44.54
Your infatuation is based[br]on a physical attraction.

00:07:44.91,00:07:48.81
Talk to the woman and you'll realize[br]you have nothing in common.

00:07:49.18,00:07:53.05
Barney, that is so insightful.[br]How did you come up with that?

00:07:53.38,00:07:55.73
It was on one of[br]these bar napkins.

00:08:02.56,00:08:03.79
[ Whimpers ]

00:08:04.46,00:08:08.01
Uh-- So, let's have[br]a conversation.

00:08:09.41,00:08:12.10
Uh, I think we'll find we[br]have very little in common.

00:08:12.52,00:08:15.61
- Can't talk. Eating.[br]- Hey, my favorite--

00:08:16.06,00:08:18.18
raspberry swirl[br]with a double glaze!

00:08:18.48,00:08:21.65
Double glaze.[br][ Gurgling ]

00:08:23.14,00:08:25.44
Oh! Okay, so we have[br]one thing in common.

00:08:25.77,00:08:29.80
But you know what I hate?[br]Drinking beer and watching TV.

00:08:30.23,00:08:32.97
Not me.[br]That's my idea of heaven.

00:08:33.38,00:08:35.38
- D'oh! Me too![br]- Really?

00:08:35.80,00:08:38.32
I can see I'm gonna love[br]working with you.

00:08:38.66,00:08:39.97
Well, gotta go.

00:08:40.28,00:08:42.62
[ Whispering ] I wanna sneak in[br]a quick nap before lunch.

00:08:42.96,00:08:45.21
[ Gasps ][br]Foul temptress.

00:08:45.51,00:08:48.57
I'll bet she thinks Ziggy's[br]gotten too preachy too.

00:08:51.25,00:08:52.92
- [ Bell Dings ][br]- [ Sighs ]

00:08:53.31,00:08:56.08
I made it the whole day[br]without seeing her again.

00:08:57.26,00:08:59.37
[ Screams ][br]I mean, hello!

00:08:59.77,00:09:01.19
[ Chuckles ]

00:09:01.53,00:09:03.00
I guess we'll be[br]going down together.

00:09:03.31,00:09:05.37
- I mean, getting off toge-- I mean--[br]- That's okay.

00:09:05.85,00:09:07.55
I'll just push the button[br]for the stimulator--

00:09:07.86,00:09:09.53
I mean, elevator.

00:09:09.95,00:09:12.76
[ Thinking ] Think unsexy thoughts.[br]Think unsexy thoughts. Think unsexy thoughts.

00:09:14.22,00:09:16.24
Oh, that's unsexy.

00:09:17.41,00:09:19.89
- " [ Humming Theme From[br]I Dream ofJeannie ][br]- Ew.!

00:09:22.10,00:09:23.39
[ Burps ]

00:09:24.34,00:09:26.06
D'oh!

00:09:26.78,00:09:28.95
[ Whispering ] Think unsexy thoughts.[br]Think unsexy thoughts.

00:09:29.94,00:09:31.68
[ Chuckles ]

00:09:32.14,00:09:33.77
Well, this is my floor.

00:09:34.77,00:09:36.61
[ Grunting, Screaming ]

00:09:37.12,00:09:38.85
See you tomorrow!

00:09:39.21,00:09:41.68
Ah, home to my loving family.

00:09:41.98,00:09:43.64
What more could a man ask for?

00:09:43.95,00:09:46.01
[ Blows Nose ]

00:09:46.37,00:09:49.31
Hi, Homer. Don't kiss me.[br]I'm all stuffed up.

00:09:49.74,00:09:51.50
- [ Groans ][br]- Hi, Dad.

00:09:51.82,00:09:54.31
Hi, son![br]How are you-- Ew!

00:09:54.67,00:09:56.33
Dad, look.[br]I made fish sticks.

00:09:56.70,00:09:59.84
They're burned on the outside, but they're[br]frozen on the inside, so it balances out.

00:10:00.24,00:10:02.04
Yeah, good.

00:10:02.42,00:10:05.27
That raccoon[br]stole my lamb chop!

00:10:07.53,00:10:10.77
Let's have a little quality time together,[br]just you and me.

00:10:11.27,00:10:13.86
- [ TV Off][br]- Oh, that's sweet. [ Sniffling ]

00:10:14.19,00:10:16.50
Guess what? There's[br]a new place at the mall...

00:10:16.85,00:10:18.68
that puts your picture[br]on a T-shirt.

00:10:18.99,00:10:21.27
I got two dollars off[br]because mine got smeared.

00:10:21.70,00:10:25.16
Ew. Hey, we haven't[br]watched TV in a while.

00:10:25.48,00:10:27.29
Tonight, Eye on Springfield[br]takes a look...

00:10:27.60,00:10:30.02
at the secret affairs of Kennedy,[br]Eisenhower, Bush and Clinton.

00:10:30.39,00:10:32.37
Did fooling around[br]on their wives make them great?

00:10:32.67,00:10:35.94
We'll find out next when we play[br]''Hail to the Cheat.''

00:10:36.27,00:10:38.08
[ Whimpers ]

00:10:38.90,00:10:40.92
[ Woman ][br]Ooh!Just do it.

00:10:40.92,00:10:42.56
- [ Screams ][br]- [ Door Closes ]

00:10:47.15,00:10:50.11
Hello, hotline?[br]I'm very tempted by another woman.

00:10:50.11,00:10:53.19
Homer Simpson,[br]that's a dilly of a pickle.

00:10:53.53,00:10:56.54
- Hey, let's conference you with Marge, huh?[br]- No!

00:10:57.98,00:10:59.33
[ Groans, Grunts ]

00:11:03.42,00:11:06.31
- Who are you?[br]- Homer, I'm your guardian angel.

00:11:06.70,00:11:10.88
I've assumed the form of someone you would[br]recognize and revere-- Sir Isaac Newton.

00:11:11.22,00:11:13.72
- Sir Isa-who?[br]- Oh, very well.

00:11:14.47,00:11:15.43
[ Gasps ]

00:11:15.74,00:11:18.13
Colonel Klink.![br]Did you ever get my letters?

00:11:18.49,00:11:22.47
- I'm not actually Colonel Klink.[br]I'm just assuming his form.[br]- [ Chuckles ]

00:11:22.82,00:11:25.60
Did you know Hogan had tunnels[br]all over your camp?

00:11:25.97,00:11:28.67
Homer! That's not why I'm here.

00:11:29.01,00:11:34.24
My job is to show you how miserable life would[br]be if you married Mindy instead of Marge.

00:11:36.27,00:11:38.26
Ooh, I would live in a big mansion?

00:11:39.90,00:11:41.73
[ Both Grunting ]

00:11:42.14,00:11:44.94
- I'm so happy, darling.[br]- I as well.

00:11:45.36,00:11:48.71
- Are you happy,Jeeves?[br]- Yes, sir. Quite.

00:11:49.07,00:11:51.48
- Then we're all happy.[br]- Let's get out of here.

00:11:52.64,00:11:55.73
Sure, life is good for you,[br]but what about Marge?

00:11:57.08,00:11:59.45
[ Gasps ][br]Marge lives here?

00:11:59.77,00:12:03.30
-[ Man ] Madam President,[br]your approval rating is soaring.[br]-[ Marge ] Mmm.

00:12:03.64,00:12:05.56
This dream is over.

00:12:06.29,00:12:07.71
[ Screaming ]

00:12:08.54,00:12:10.06
[ Grunting ]

00:12:10.38,00:12:12.26
Hey, you,[br]get out of my office!

00:12:12.88,00:12:15.13
- Nerd![br]- [ Kids Taunting ]

00:12:17.57,00:12:19.95
You're goofy-looking.[br][ Laughing ]

00:12:20.36,00:12:21.84
[ All Grunting ]

00:12:24.13,00:12:26.19
[ Panting ][br]Whoa!

00:12:28.48,00:12:30.50
- What the hell?[br]- Shh!

00:12:32.71,00:12:34.48
[ Murmuring ]

00:12:39.32,00:12:42.31
- What is this place?[br]- The refuge of the damned.

00:12:42.65,00:12:45.25
A place where we can work on[br]our extra-credit assignments...

00:12:45.61,00:12:47.70
without fear of reprisal.

00:12:48.17,00:12:50.20
Come, you must be tired[br]from the chase.

00:12:50.53,00:12:54.06
Oliver, bring our friend a hard-boiled egg[br]and some prune juice.

00:12:54.56,00:12:56.78
Finally, Bart's one of us.

00:12:57.17,00:12:58.85
[ Kids ][br]Excelsior!

00:12:59.16,00:13:04.36
" Oh, Mindy, you came[br]and you gave without flaking "

00:13:04.73,00:13:06.78
" But I sent you BenGay "

00:13:07.09,00:13:09.44
" Oh, Andy, you kissed me "

00:13:09.77,00:13:11.94
"And stopped me[br]from something "

00:13:12.41,00:13:14.11
"And I-- "[br]Uh-oh.

00:13:14.45,00:13:17.05
- Dad, why are you singing?[br]- [ Thinking ] Tell a lie. Tell a lie.

00:13:17.49,00:13:20.38
Because I have a small role[br]in a Broadway musical.

00:13:20.72,00:13:22.36
It's not much, but it's a start.

00:13:22.81,00:13:25.80
- [ Thinking ] Bravo.[br]- [ Lone Clapping ]

00:13:26.14,00:13:28.18
- Are you hiding something from me?[br]- Like what?

00:13:28.50,00:13:30.54
Judging from your song,[br]you're infatuated...

00:13:30.87,00:13:33.14
with a woman named Mindy[br]or a man named Andy.

00:13:33.42,00:13:35.92
- Lisa, look out behind you![br]- Dad, I'm not gonna fall for that.

00:13:35.92,00:13:39.16
No, Lisa, I swear to you![br]I'm 1 00% completely serious!

00:13:39.90,00:13:41.74
You've gotta turn around[br]right now before it's too late!

00:13:42.07,00:13:43.84
- Huh?[br]- Sucker!

00:13:44.85,00:13:47.94
''Mindy, because of our[br]uncontrollable attraction...

00:13:48.31,00:13:51.09
I think we should avoid[br]each other from now on.''

00:13:51.54,00:13:55.73
''Max, what I did,[br]I did because of alcohol and anger.''

00:13:56.08,00:13:58.68
''I'm tired of these jokes[br]about my giant hand.

00:13:59.05,00:14:01.85
The first such incident[br]occurred in 1 956 when''--

00:14:02.28,00:14:04.51
- Hi, Homer.[br]- Mindy! Uh-- [ Clears Throat ]

00:14:05.13,00:14:07.67
Oh, no, I'm sweating[br]like Roger Ebert.

00:14:08.16,00:14:11.88
Mu-- Murphy, youse--[br]You are a elf--

00:14:12.39,00:14:15.78
Uncontrollably, I think--

00:14:16.10,00:14:18.15
[ Gibberish ]

00:14:18.65,00:14:21.39
Look at those two[br]inseparable chums, Smithers.

00:14:21.73,00:14:25.06
That's exactly the teamwork we'd like to[br]showcase at this year's energy convention.

00:14:25.37,00:14:30.64
- Are you sure, sir?[br]- Well, no one else seems to share[br]the same spirit of camaraderie.

00:14:32.39,00:14:34.49
[ Gibberish Continues ]

00:14:35.33,00:14:37.34
Simpson, Simmons,[br]you two have been chosen...

00:14:37.65,00:14:39.45
to represent us at[br]the National Energy Convention.

00:14:39.70,00:14:43.10
Congratulations. You'll be spending two nights[br]together in glamorous Capital City.

00:14:43.41,00:14:46.21
Wow! Capital City!

00:14:46.59,00:14:48.25
The Windy Apple!

00:14:48.56,00:14:50.36
Come on.[br]I'll get you the tickets.

00:14:50.70,00:14:53.70
Oh, this is the worst crisis[br]my marriage has ever faced!

00:14:54.04,00:14:57.42
Colonel Klink,[br]why have you forsaken me?

00:14:57.76,00:15:00.28
- What is it? You have a question?[br]- [ Chuckling ]

00:15:00.63,00:15:03.05
Did you know Kinch had[br]a radio in the coffee pot?

00:15:03.38,00:15:05.77
He did? Mmm!

00:15:06.71,00:15:07.94
[ Groans ]

00:15:14.29,00:15:18.62
TV's there, bathroom's there,[br]and there's your king-sized bed for--

00:15:19.02,00:15:20.55
[ Wolf Whistle, Meowing ]

00:15:20.55,00:15:23.00
[ Imitates Bed Squeaking, Growls, Pants ]

00:15:23.00,00:15:24.69
[ Barking, Howling ]

00:15:25.10,00:15:26.79
[ Gibberish ][br]Hubba-hubba.

00:15:27.13,00:15:28.76
Stop that![br]I love my wife and family.

00:15:28.76,00:15:32.00
All I'm gonna use this bed for is sleeping,[br]eating and maybe building a little fort.

00:15:32.35,00:15:33.60
That's it!

00:15:34.47,00:15:36.71
[ Gasps ][br]Free mouthwash! Free shampoo!

00:15:37.70,00:15:41.16
- Free shower curtain![br]- [ Mindy ] Free shower curtain.!

00:15:41.51,00:15:43.13
- Mindy?[br]- Homer?

00:15:44.69,00:15:48.69
Wow. If it weren't for this wall,[br]we'd be sleeping in the same bed.

00:15:49.01,00:15:53.14
Yeah. Uh, walls are a necessity[br]in today's society. [ Chuckles ]

00:15:53.44,00:15:57.67
Homer, I got a really wicked idea[br]that could get us into a lot of trouble.

00:15:58.41,00:16:01.68
Oh! Mindy, we have to fight[br]our temptation.

00:16:02.02,00:16:06.96
No, Homer. Let's do it.[br]Let's call room service!

00:16:06.96,00:16:08.85
- Oh.

00:16:09.24,00:16:10.91
- [ Lips Smacking ][br]- Mmm!

00:16:11.45,00:16:14.80
- I can't believe we ordered so much.[br]- Oh, something's missing.

00:16:15.28,00:16:17.62
Ooh! One of the turkeys[br]fell behind the bed.

00:16:18.53,00:16:23.26
[ Both ][br]Mmm. Foot-long chili dog.

00:16:28.02,00:16:29.36
[ Both Gasp ]

00:16:30.45,00:16:33.64
[ Marge's Voice.:[br]Mechanical Humming Sound ]

00:16:34.25,00:16:35.81
[ Screams ][br]It's a sign!

00:16:36.39,00:16:38.97
- [ Shouts ][br]- [ Mechanical Hum Continues ]

00:16:42.13,00:16:44.57
Good news, honey.[br]Two weeks are up.

00:16:44.93,00:16:46.75
You don't have to wear[br]your glasses anymore.

00:16:47.07,00:16:49.10
And your scalp[br]and posture seem fine.

00:16:49.54,00:16:51.17
Yes![br][ Grunts ]

00:16:51.40,00:16:53.53
We've been doing a lot[br]of upper-body work on Bart.

00:16:53.78,00:16:56.32
- Today, let's pound his kidneys.[br]- Yeah.

00:16:56.90,00:16:58.94
- " [ Humming ][br]- Let's get-- Huh?

00:17:01.27,00:17:02.72
What gives?

00:17:04.12,00:17:06.46
Gentlemen, the nerd[br]you knew is dead.

00:17:06.84,00:17:09.32
Beat me, and you will be[br]beating one of your own.

00:17:10.21,00:17:12.69
- Whatever.[br]- [ Blows Landing ]

00:17:13.42,00:17:14.93
[ Electricity Buzzing ]

00:17:15.44,00:17:17.91
Thanks for poisoning[br]the planet, bastard!

00:17:18.19,00:17:20.31
- Get bent![br]- No more Chernobyls!

00:17:20.66,00:17:22.66
- Go to hell! [ Grunts ][br]- [ Man Shouts ]

00:17:23.01,00:17:26.66
You know, I was a little worried about[br]coming to this convention with you.

00:17:26.96,00:17:29.12
But I think as long as[br]we're not alone together--

00:17:29.51,00:17:30.93
[ Man ] And now the moment[br]you've been waiting for.

00:17:30.93,00:17:33.57
This year's King and Queen[br]of Energy are...

00:17:33.92,00:17:36.81
Homer Simpson[br]and Mindy Simmons.

00:17:37.30,00:17:39.75
- Huh?[br]- "[ Fanfare ]

00:17:40.16,00:17:43.32
Homer, Mindy, you've just won a romantic[br]dinner alone at Madame Chao's...

00:17:43.65,00:17:46.60
the sexiest Chinese restaurant[br]in Capital City!

00:17:46.93,00:17:49.08
- Is there any way to get out of this?[br]- No.

00:17:51.54,00:17:53.66
"[ Romantic ]

00:17:58.75,00:17:59.80
[ Sighs ]

00:18:00.11,00:18:01.57
What a perfect evening.

00:18:01.84,00:18:04.24
It was sure nice of them[br]to make us cheeseburgers.

00:18:04.57,00:18:06.27
Uh, yeah.

00:18:08.28,00:18:10.68
[ Reading Silently ][br]''You will find happiness with a new love.''

00:18:11.12,00:18:14.43
Oh, even the Chinese are against me.[br][ Groans ]

00:18:14.43,00:18:16.65
What's the point?[br]I can't fight fate.

00:18:17.14,00:18:18.41
[ Slurping ]

00:18:19.68,00:18:22.30
Hey, we're out of[br]these ''new love'' cookies.

00:18:22.64,00:18:25.01
Well, open up the[br]''stick with your wife'' barrel.

00:18:27.64,00:18:30.54
Well, I guess[br]you'll wanna come in.

00:18:30.94,00:18:32.90
- Okay.[br]- ''Okay.''

00:18:33.53,00:18:35.37
This was a really[br]nice night, Homer.

00:18:35.78,00:18:37.29
Yeah, yeah.

00:18:37.66,00:18:39.28
[ Sobbing ]

00:18:39.63,00:18:42.76
- What's wrong?[br]- Oh, yeah. Like you don't know.

00:18:43.30,00:18:45.99
- We're gonna have sex.[br]- Oh.

00:18:46.54,00:18:49.28
Well, we don't have to.

00:18:49.66,00:18:52.66
Yes, we do.[br]The cookie told me so.

00:18:53.04,00:18:56.08
Well, desserts[br]aren't always right.

00:18:56.40,00:18:58.05
But they're so sweet.

00:18:58.77,00:18:59.95
Homer...

00:19:00.58,00:19:02.92
you don't have to do anything[br]you don't want to.

00:19:04.63,00:19:07.56
Well, maybe I want to.

00:19:08.14,00:19:10.59
But then I think about[br]Marge and the kids.

00:19:11.25,00:19:13.15
Well, not the boy.[br]He drives me nuts.

00:19:13.15,00:19:15.78
- Sometimes I'd just like to--[br]- Homer...

00:19:17.28,00:19:21.84
you know how I feel,[br]so it's up to you.

00:19:22.77,00:19:26.42
Look in your heart.[br]I think you'll see what you want.

00:19:42.17,00:19:44.73
- Oh, baby.[br]- "[ Man Singing ]

00:19:45.10,00:19:48.12
This was[br]a wonderful idea, Homie.

00:19:49.96,00:19:51.89
Hey, there's a turkey[br]behind the bed!

00:19:52.47,00:19:55.14
Mmm. Marge.

00:19:55.92,00:19:57.62
[ Chuckling ]

00:19:58.23,00:20:02.79
[ Homer] " Oh, Margie, you came[br]and you found me a turkey "

00:20:03.24,00:20:06.90
" On my vacation[br]away from workie "

00:20:07.31,00:20:09.10
[ Wolf Whistle, Meowing ]

00:20:09.48,00:20:12.06
[ Imitating Bed Squeaking, Growls, Pants ]

00:20:12.65,00:20:14.65
[ Barking, Howling ]

00:20:15.03,00:20:16.14
[ Gibberish ][br]Hubba-hubba.

00:20:16.66,00:20:18.22
[ Blow Lands ]

